baseurl = "https://obsidianshark.gitlab.io/hugo-cv-site/"
#relativeURLs = true
#canonifyURLs = true
title = "Jordan Handy"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20  # Pagination for blog posts

pygmentsstyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji=true
disqusShortname = "hifx93"

[params]
  author = "Jordan Handy"
  info = ["Full Stack Developer","Cloud Solutions Architect"]
  description = "Jordan Handy | Full Stack Developer & Technical Consultant"
  keywords = "blog,developer,personal,fullstack,full,stack,technical,consultant,specialist"
  #avatarurl = "images/avatar.jpg"
  gravatar = "handy.jordan@outlook.com"
  dateFormat = "January 2, 2006"
  #favicon_32 = "/img/favicon-32x32.png"
  #favicon_16 = "/img/favicon-16x16.png"


  # footercontent = "Jordan Handy"
  #hideFooter = false
  #hideCredits = true
  #hideCopyright = false
  since = 2008
  # commit = "https://gitlab.com/obsidianshark/hugo-cv/tree/"
  rtl=false
  colorScheme="dark"
  hideColorSchemeToggle = false
  enableTwemoji = true
  maxSeeAlsoItems=5

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://linkedin.com/in/jordan-handy"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/jordanhandy/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 3
  url = "https://gitlab.com/obsidianshark/"
[[params.social]]
  name = "NPM"
  icon = "fa fa-nodejs"
  weight = 4
  url = "https://www.npmjs.com/~jordanhandy"
[[params.social]]
  name = "KoFi"
  icon = "fa fa-coffee"
  weight = 5
  url = "https://www.npmjs.com/~jordanhandy"
[[params.social]]
  name = "Newsletter"
  icon = "fa fa-newspaper-o fa-2x"
  weight = 6
  url = "https://newsletter-signup93.herokuapp.com/"

[languages.en]
languageName = ":us:"

# Menu links
[[languages.en.menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[languages.en.menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[languages.en.menu.main]]
  name = "Certifications"
  weight = 3
  url = "certifications/"
[[languages.en.menu.main]]
  name = "Portfolio"
  weight = 4
  url = "portfolio/portfolio"
[[languages.en.menu.main]]
  name = "Service"
  weight = 5
  url = "service/"
[[languages.en.menu.main]]
  name = "Contact"
  weight = 6
  url = "contact/"
[[languages.en.menu.main]]
  name = "Interactive Resume"
  weight = 7
  url = "intresume/"
