baseurl = "https://obsidianshark.gitlab.io/hugo-cv-site/"
relativeURLs = true
canonifyURLs = true
title = "Jordan Handy"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20  # Pagination for blog posts

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Jordan Handy"
  info = "Full Stack DevOps and Technical Consultant"
  description = "Jordan's Website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  gravatar = "handy.jordan@outlook.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  # footercontent = "Jordan Handy"
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = "2008"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/johndoe/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Certifications"
  weight = 3
  url = "certifications/"
