baseurl = "https://obsidianshark.gitlab.io/hugo-cv-site/"
relativeURLs = true
canonifyURLs = true
title = "Jordan Handy"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20  # Pagination for blog posts

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "hifx93"

[params]
  author = "Jordan Handy"
  info = "Full Stack Developer and Cloud Solutions Architect"
  description = "Jordan Handy | Full Stack Developer & Technical Consultant"
  keywords = "blog,developer,personal,fullstack,full,stack,technical,consultant,specialist"
  #avatarurl = "images/avatar.jpg"
  gravatar = "handy.jordan@outlook.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  # footercontent = "Jordan Handy"
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = "2008"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://linkedin.com/in/jordan-handy"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/jordanhandy/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 3
  url = "https://gitlab.com/obsidianshark/"
[[params.social]]
  name = "NPM"
  icon = "fa fa-nodejs"
  weight = 4
  url = "https://www.npmjs.com/~jordanhandy"
[[params.social]]
  name = "KoFi"
  icon = "fa fa-coffee"
  weight = 5
  url = "https://www.npmjs.com/~jordanhandy"
[[params.social]]
  name = "Newsletter"
  icon = "fa fa-newspaper-o fa-2x"
  weight = 6
  url = "https://newsletter-signup93.herokuapp.com/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Certifications"
  weight = 3
  url = "certifications/"
[[menu.main]]
  name = "Portfolio"
  weight = 4
  url = "portfolio/portfolio"
[[menu.main]]
  name = "Contact"
  weight = 5
  url = "contact/"
[[menu.main]]
  name = "Interactive Resume"
  weight = 6
  url = "intresume/"
