# Typical Netlify CMS configuration for a Hugo-based blog
#  (/static/admin/config.yml)

backend:
  name: git-gateway
  branch: main

# Where our media (usually images) content lives in the Git repository
media_folder: "static/img/uploads"

# Where our media is found in the live site
public_folder: "/img/uploads"

# Show website URL for easy navigation while within CMS admin
display_url: "https://www.jordanhandy.com"

# The various content types for your site.
#  Common options are "posts, blog, news"
#  See https://www.netlifycms.org/docs/add-to-your-site/#collections
collections:
    # Unique identifier for this collection
  - name: post

    # What this collection is called in the UI (i.e. friendly name)
    label: Post

    # Where the content lives in our Git repository
    folder: "content/posts"

    # Allow users to create new content?
    create: true

    # The relative URL for the post.
    #  Default is {{slug}}, a URL-safe version of the title
    slug: "{{slug}}"

    # The fields shown in the content editor.
    #  They correspond to fields in the front matter (except for 'body')
    fields:
       # Title of your posts
    - {label: "Title", name: "title", widget: "string" }

    - {label: "Last updated", name: "date", widget: "date" }

    # (Alternative YAML syntax)
      # 'label' is what we call this field in the UI.
      #  Makes it easier for your content creators to understand what the field is for,
      #   especially if your front matter uses strange names.
    - label: "Original publish date"

      # The name of the field in your front matter
      name: "publishdate"

      # The UI widget we use to display and interact with this field.
      #  See https://www.netlifycms.org/docs/widgets/ for widget documentation.
      widget: "date"

      # Summary field. The "text" widget handles multiline input.
    - {label: "Summary", name: "description", widget: "text"}

      # Our "draft" field uses the "boolean (true/false)" widget
      #  and attempts to make it's purpose clearer to content creators.
      # We default it to "true" so we don't accidentally post rough drafts.
    - {label: "Draft (not published)", name: "draft", widget: "boolean", default: true}

    - {label: "Authors", name: "authors", widget: "list", default: ["Joe Author"]}

      # Notice this "url" field uses the "hidden" widget, meaning that
      #  it won't appear in the UI, but it will still update our front matter.
    - {label: "Link", name: "url", widget: "hidden", default: "{{slug}}"}

    # These "categories" and "tags" fields use the "list" widget
    - label: "Categories"
      name: "categories"
      required: true
      widget: "list"
      field: {label: "Category", name: "category_name", widget: "string"}


    - label: "Tags"
      name: "Tags"
      widget: "list"
      field: {label: "Tag", name: "tag_name", widget: "string"}


    # body: Super important if you want to actually edit the content of your posts. :)
    - label: "Article"
      name: "body"
      widget: "markdown"
